services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST= #your_public_ip
      - PASSWORD_HASH= #your_webui_password
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.0.8.x
      - WG_DEFAULT_DNS=94.140.14.14,94.140.15.15
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=10
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /DATA/AppData/wg-easy/data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
