services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    network_mode: none
    environment:
      - AUTOHEAL_CONTAINER_LABEL=healthcheck
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped