services:
  glances:
    container_name: glances
    image: nicolargo/glances:4.1.2.1-full
    ports:
      - 61208:61208
    environment:
      - TZ=Asia/Makassar
      - GLANCES_OPT=-w --disable-webui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
