services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:latest
    ports:
      - 8008:80
    volumes:
      - /DATA/AppData/fireshare/data:/data
      - /DATA/AppData/fireshare/processed:/processed
      - /DATA/AppData/fireshare/videos:/videos
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - SECRET_KEY=fireclipsnetworkawhare
      - MINUTES_BETWEEN_VIDEO_SCANS=0
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
