services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - 8081:8081
      - 6881:6881
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /DATA/AppData/qbittorrent/config:/config
      - /DATA/AppData/qbittorrent/vuetorrent:/vuetorrent
      - /DATA/Media/downloads:/downloads
    restart: unless-stopped
