services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
    volumes:
      - /DATA/AppData/bazarr/config:/config
      - /DATA/Media/movies:/movies
      - /DATA/Media/tv:/tv
    restart: unless-stopped
