services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
    volumes:
      - /DATA/AppData/radarr/config:/config
      - /DATA/Media/movies:/movies
      - /DATA/Media/downloads:/downloads
    restart: unless-stopped
