name: pingvin-share
services:
  app:
    image: stonith404/pingvin-share:latest
    ports:
      - 8090:3000
    volumes:
      - '/DATA/AppData/pingvin-share/data:/opt/app/backend/data'
      - '/DATA/AppData/pingvin-share/images:/opt/app/frontend/public/img'
    restart: unless-stopped
