services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command:
      - --cleanup=true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
