services:
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    command:
      - --cleanup=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
