services:
  gethomepage:
    container_name: homepage
    image: gethomepage/homepage:v0.10.9
    ports:
      - 3002:3000
    volumes:
      - /DATA/AppData/homepage/config:/app/config
      - /DATA/AppData/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
