services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Makassar
    ports:
      - 5055:5055
    volumes:
      - /DATA/AppData/jellyseerr/config:/app/config
    restart: unless-stopped
