services:
  picoshare:
    container_name: pico-share
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=cute!pass #Change_password
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - /DATA/Apdata/pico-share/data:/data
    restart: unless-stopped
