services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 8065:8080
    volumes:
      - /run/udev:/run/udev:ro
      - /DATA/AppData/scrutiny/config:/opt/scrutiny/config
      - /DATA/AppData/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sda
      - /dev/sdb
    restart: unless-stopped
