services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:latest
    privileged: true
    cap_add:
      - SYS_RAWIO
    ports:
      - 8065:8080
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/nvme0n1
      - /dev/sda
    restart: unless-stopped
