services:
  routeros:
    container_name: routeros
    image: evilfreelancer/docker-routeros:6.48.3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8280:80" #HTTP
      - "8291:8291" #Winbox
