services:
  jdownloader2:
    container_name: jdownloader2
    image: jlesage/jdownloader-2
    restart: unless-stopped
    ports:
      - 5800:5800
    environment:
      - TZ=Asia/Makassar
    volumes:
      - /DATA/AppData/jdownloader2/config:/config
      - /DATA/Downloads:/output
