services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
    volumes:
      - /DATA/AppData/sonarr/config:/config
      - /DATA/Media/downloads:/downloads
      - /DATA/Media/tv:/tv
    restart: unless-stopped
