services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    ports:
      - 3081:8081
    volumes:
      - /DATA/AppData/metube/cookies:/cookies
      - /DATA/AppData/metube/downloads:/downloads
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
      - DEFAULT_OPTION_PLAYLIST_ITEM_LIMIT=5
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
      - DEFAULT_OPTION_PLAYLIST_STRICT_MODE=true
