services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: my-docker
    container_name: tailscale
    environment:
      - TS_AUTHKEY= #ts-oauth-key-client?ephemeral=false
      - TS_ROUTES=192.168.1.0/24,192.168.100.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /DATA/AppData/tailscale/data:/var/lib/tailscale
