services:
  medis:
    image: ghcr.io/raw-network/medis:latest
    container_name: medis
    network_mode: container:gluetun
    ports:
      - 3073:3000
    volumes:
      - /DATA/AppData/medis/videos:/videos
      - /DATA/AppData/medis/cookies:/cookies
    environment:
      - TZ=Asia/Makassar
      - MAX_QUEUE_LIMIT=5
    restart: unless-stopped