services:
  medis:
    image: ghcr.io/raw-network/medis:latest
    container_name: medis
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
      - ./cookies:/cookies
    environment:
      - TZ=UTC
      - MAX_QUEUE_LIMIT=10
      - AUTO_UPDATE_YTDLP=false
      - PLAYLIST_DOWNLOAD_LIMIT=1
    restart: unless-stopped
