services:
    l2tp-server:
        privileged: true
        ports:
            - 1701:1701/udp
        container_name: l2tp-server
        restart: unless-stopped
        environment:
            - VPN_USER= #l2tp_user
            - VPN_PASSWORD= #l2tp_pass
        volumes:
            - /DATA/AppData/l2tp-server/data:/etc/ipsec.d
            - /lib/modules:/lib/modules:ro
        image: gritsenko/l2tp_without_ipsec:latest
