services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    ports:
      - 2333:2333
    volumes:
      - ./config/application.yml:/opt/Lavalink/application.yml
    restart: unless-stopped