services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    ports:
      - 8086:8080
    volumes:
      - /DATA/AppData/stirling/trainingData:/usr/share/tessdata
      - /DATA/AppData/stirling/extraConfigs:/configs
      - /DATA/AppData/stirling/logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    restart: unless-stopped
