services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /DATA:/srv
      - /DATA/AppData/filebrowser/database:/database
      - /DATA/AppData/filebrowser/config:/config
    ports:
      - 8095:80
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
