services:
  filebrowser:
    image: filebrowser/filebrowser:v2.32.0
    container_name: filebrowser
    volumes:
      - /DATA:/srv
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8095:80
    restart: unless-stopped
