services:
  filebrowser:
    image: filebrowser/filebrowser:v2.31.2
    container_name: filebrowser
    volumes:
      - /DATA:/srv
    ports:
      - 8095:80
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
